CatalogAppMVC/CatalogAppMVC/Controllers/ManageAccountController.cs
using CatalogAppMVC.Models.Identity;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CatalogAppMVC.Models;
using CatalogAppMVC.Models.WorkLinqToSql;
using CatalogAppMVC.Models.Identity.IdentityViewModel;
using System.Threading.Tasks;
using System.Threading;
using CatalogAppMVC.Models.interfaces;

namespace CatalogAppMVC.Controllers
{
    public class ManageAccountController : Controller
    {

        private ApplicationUserManager _userManager;
        private ApplicationSignInManager _signInManager;

        internal ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        internal ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set { _signInManager = value; }
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private CustomRoleStore _roleStore;

        private CustomRoleStore RoleStore
        {
            get
            {
                if (_roleStore == null)
                {
                    _roleStore = new CustomRoleStore(HttpContext.GetOwinContext().Get<ApplicationDbContext>());
                    return _roleStore;
                }
                else
                {
                    return _roleStore;
                }
            }
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult GetListUsers()
        {
            try
            {
                var listUsers = UserManager.Users.ToList<ApplicationUser>();

                if (listUsers != null)
                {
                    List<ApplicationUser> sortListUser = new List<ApplicationUser>();

                    foreach (var user in listUsers)
                    {
                        if (user.IsActivated == false)
                        {
                            sortListUser.Add(user);
                        }
                    }
                    foreach (var user in listUsers)
                    {
                        if (user.IsActivated == true)
                        {
                            sortListUser.Add(user);
                        }
                    }

                    UsersViewModel model = new UsersViewModel();
                    model.Users = new List<UserViewModel>();

                    for (int i = 0; i < sortListUser.Count; i++)
                    {
                        UserViewModel userModel = new UserViewModel()
                        {
                            UserName = sortListUser[i].UserName,
                            Email = sortListUser[i].Email,
                            IsActivate = sortListUser[i].IsActivated
                        };

                        model.Users.Add(userModel);
                    }

                    return View(model);
                }

                return View();

            }
            catch
            {
                return View("_AppError");
            }
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult ActivateUser()
        {
            ActivateUserViewModel model = new ActivateUserViewModel();
            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> ActivateUser(ActivateUserViewModel model)
        {
            try
            {
                if (model != null)
                {
                    var _user = await UserManager.FindByEmailAsync(model.Email);

                    if (_user != null)
                    {
                        _user.IsActivated = true;
                        await UserManager.UpdateAsync(_user);
                        return RedirectToAction("GetListUsers");
                    }
                    else
                    {
                        return View("_AppError");
                    }
                }

                return View();
            }
            catch
            {
                return View("_AppError");
            }
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteUser()
        {
            DeleteUserViewModel model = new DeleteUserViewModel();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> DeleteUser(DeleteUserViewModel model)
        {
            try
            {
                if (model != null)
                {
                    var _user = await UserManager.FindByEmailAsync(model.Email);

                    if (_user == null)
                    {
                        _user = await UserManager.FindByNameAsync(model.Name);
                    }

                    if (_user.Id != Access.ADMINID & _user.Id != Access.GUESTID)
                    {
                        await UserManager.DeleteAsync(_user);
                        return RedirectToAction("GetListUsers");
                    }
                    else
                    {
                        return View("_AppError");
                    }
                }

                return View();
            }
            catch
            {
                return View("_AppError");
            }
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult AddUserToRole()
        {
            AddUserToRoleViewModel model = new AddUserToRoleViewModel();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> AddUserToRole(AddUserToRoleViewModel model)
        {
            try
            {
                if (model != null)
                {
                    var _user = await UserManager.FindByEmailAsync(model.Email);

                    if (_user != null)
                    {
                        await UserManager.AddToRoleAsync(_user.Id, model.NameRole);
                        return RedirectToAction("GetListUsers");
                    }
                    else
                    {
                        return View("_AppError");
                    }
                }

                return View();
            }
            catch
            {
                return View("_AppError");
            }
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteUserFromRole()
        {
            AddUserToRoleViewModel model = new AddUserToRoleViewModel();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> DeleteUserFromRole(AddUserToRoleViewModel model)
        {
            try
            {
                if (model != null)
                {
                    var _user = await UserManager.FindByEmailAsync(model.Email);

                    if (_user != null)
                    {
                        if (_user.Id != 1 & model.NameRole != "Administrator")
                        {
                            if (_user.Id != 2 & model.NameRole != "Guest")
                            {
                                await UserManager.AddToRoleAsync(_user.Id, model.NameRole);
                                return RedirectToAction("GetListUsers");
                            }
                        }

                        return View("_AppError");
                    }
                }

                return View();
            }
            catch
            {
                return View("_AppError");
            }
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult GetListRoles()
        {

            try
            {
                var listRoles = RoleStore.Roles.ToList();

                if (listRoles != null)
                {

                    if (listRoles != null)
                    {

                        RolesViewModel model = new RolesViewModel();
                        model.Roles = new List<RoleViewModel>();

                        foreach (var role in listRoles)
                        {

                            RoleViewModel roleModel = new RoleViewModel() { Name = role.Name };
                            model.Roles.Add(roleModel);

                        }

                        return View(model);
                    }

                    return View();
                }

                return View();
            }
            catch
            {
                return View("_AppError");
            }
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult AddRole()
        {
            AddRoleViewModel model = new AddRoleViewModel();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> AddRole(AddRoleViewModel model)
        {
            try
            {
                if (model != null)
                {
                    CustomRole _customRole = new CustomRole(model.Name);
                    await RoleStore.CreateAsync(_customRole);
                    return RedirectToAction("GetListRoles");
                }
                else
                {

CatalogAppMVC/CatalogAppMVC/Views/ManageAccount/ActivateUser.cshtml
@model CatalogAppMVC.Models.Identity.IdentityViewModel.ActivateUserViewModel

@{
    ViewBag.Title = "ActivateUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_AdminNavPartial")

<br />

<h2>Модерация пользователя</h2>

<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActivate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActivate)
                    @Html.ValidationMessageFor(model => model.IsActivate, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Активировать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

CatalogAppMVC/CatalogAppMVC/Views/ManageAccount/AddRole.cshtml
@model CatalogAppMVC.Models.Identity.IdentityViewModel.AddRoleViewModel

@{
    ViewBag.Title = "AddRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_AdminNavPartial")

<br />

<h2>Добавление роли</h2>

<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

CatalogAppMVC/CatalogAppMVC/Views/ManageAccount/AddUserToRole.cshtml
@model CatalogAppMVC.Models.Identity.IdentityViewModel.AddUserToRoleViewModel

@{
    ViewBag.Title = "AddUserToRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_AdminNavPartial")

<br />

<h2>Добавление пользователя в группу</h2>

<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameRole, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameRole, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameRole, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

CatalogAppMVC/CatalogAppMVC/Views/ManageAccount/CreateAccess.cshtml
@model CatalogAppMVC.Models.AccessRoleCategory

@{
    ViewBag.Title = "Права";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Создание прав доступа</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AccessRoleCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RoleID, "Роль", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RoleID, ViewBag.Roles as SelectList)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "Категория", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryID, ViewBag.Categories as SelectList)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CanRead, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CanRead)
                    @Html.ValidationMessageFor(model => model.CanRead, "Чтение", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CanWrite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CanWrite)
                    @Html.ValidationMessageFor(model => model.CanWrite, "Запись", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CanDownloadFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CanDownloadFile)
                    @Html.ValidationMessageFor(model => model.CanDownloadFile, "Скачивание", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "AccessCategoryList")
</div>

CatalogAppMVC/CatalogAppMVC/Views/ManageAccount/CreateCategory.cshtml
@model CatalogAppMVC.Models.Category

@{
    ViewBag.Title = "Создание категории";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Создание категории</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Название", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "ListCategory")
</div>

CatalogAppMVC/CatalogAppMVC/Views/ManageAccount/DeleteRole.cshtml
@model CatalogAppMVC.Models.Identity.IdentityViewModel.AddRoleViewModel

@{
    ViewBag.Title = "DeleteRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_AdminNavPartial")

<br />

<h2>Удаление роли</h2>

<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Удалить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

CatalogAppMVC/CatalogAppMVC/Views/ManageAccount/DeleteUser.cshtml
@model CatalogAppMVC.Models.Identity.IdentityViewModel.DeleteUserViewModel

@{
    ViewBag.Title = "DeleteUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_AdminNavPartial")

<br />

<h2>Удаление пользователя</h2>

<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Удалить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

CatalogAppMVC/CatalogAppMVC/Views/ManageAccount/DeleteUserFromRole.cshtml
@model CatalogAppMVC.Models.Identity.IdentityViewModel.AddUserToRoleViewModel

@{
    ViewBag.Title = "DeleteUserFromRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_AdminNavPartial")

<br />

<h2>Удаление пользователя из группы</h2>

<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameRole, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameRole, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameRole, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Удалить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

CatalogAppMVC/CatalogAppMVC/Views/ManageAccount/EditAccess.cshtml
@model CatalogAppMVC.Models.AccessRoleCategory

@{
    ViewBag.Title = "Права";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редактирование прав доступа</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Model.GetNameRole - @Model.GetNameCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CanDownloadFile, "Чтение", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CanRead)
                    @Html.ValidationMessageFor(model => model.CanRead, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CanDownloadFile, "Запись", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CanWrite)
                    @Html.ValidationMessageFor(model => model.CanWrite, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CanDownloadFile,"Скачивание", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CanDownloadFile)
                    @Html.ValidationMessageFor(model => model.CanDownloadFile, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

CatalogAppMVC/CatalogAppMVC/Views/ManageAccount/GetListUsers.cshtml
@model CatalogAppMVC.Models.Identity.IdentityViewModel.UsersViewModel

@{
    ViewBag.Title = "GetListUsers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_AdminNavPartial")

@using (Html.BeginForm())
{
    <ul class="list-group">

        @for (int i = 0; i < Model.Users.Count; i++)
        {
            <li class="list-group-item">
                Логин: @Model.Users[i].UserName
                <br />
                E-mail: @Model.Users[i].Email
                <br />
                Модерация: @Model.Users[i].IsActivate
            </li>
        }

    </ul>
}

CatalogAppMVC/CatalogAppMVC/Views/ManageAccount/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_AdminNavPartial")

<br />

<h3>Добро пожаловать в административную панель.</h3>

<br />

<ul class="list-group">
    
    <li class="list-group-item">
        @Html.ActionLink("Пользователи", "GetListUsers", "ManageAccount")
    </li>
    <li class="list-group-item">
        @Html.ActionLink("Группы", "GetListRoles", "ManageAccount")
    </li>
    <li class="list-group-item">
        @Html.ActionLink("Активировать польз.", "ActivateUser", "ManageAccount")
    </li>
    <li class="list-group-item">
        @Html.ActionLink("Удалить польз.", "DeleteUser", "ManageAccount")
    </li>
    <li class="list-group-item">
        @Html.ActionLink("Добавить в гр.", "AddUserToRole", "ManageAccount")
    </li>
    <li class="list-group-item">
        @Html.ActionLink("Удалить из гр.", "DeleteUserFromRole", "ManageAccount")
    </li>
    <li class="list-group-item">
        @Html.ActionLink("Добавить группу", "AddRole", "ManageAccount")
    </li>
    <li class="list-group-item">
        @Html.ActionLink("Удалить группу", "DeleteRole", "ManageAccount")
    </li>
    <li class="list-group-item">
        @Html.ActionLink("Категории", "ListCategory", "ManageAccount")
    </li>

</ul>

CatalogAppMVC/CatalogAppMVC/Views/ManageAccount/ListCategory.cshtml
@model IEnumerable<CatalogAppMVC.Models.Category>

@{
    ViewBag.Title = "Категории";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_AdminNavPartial")

<br />

<h2>Категории</h2>

<br />

<p>
    @Html.ActionLink("Создать", "CreateCategory")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Название")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Изменить", "EditCategory", new { categoryId = item.ID }) |
            @Html.ActionLink("Удалить", "DeleteCategory", new { categoryId=item.ID })
        </td>
    </tr>
}

</table>

CatalogAppMVC/CatalogAppMVC/Views/ManageAccount/ListMandatSpecification.cshtml
@model IEnumerable<CatalogAppMVC.Models.Specification>

@{
    ViewBag.Title = "ListMandatSpecification";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Обязательные спецификации</h2>

<p>
    @Html.ActionLink("Создать", "CreateMandatSpecification", new { categoryId = (int)ViewBag.CategoryID })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Название")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Удалить", "DeleteMandatSpecification", new { specificationID = item.ID, categoryId = (int)ViewBag.CategoryID })
        </td>
    </tr>
}

</table>

CatalogAppMVC/CatalogAppMVC/Views/ManageAccount/ParserContr.cshtml
@{
    ViewBag.Title = "ParserContr";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Парсер</h2>

@using (Html.BeginForm("ParserContr", "ManageAccount", FormMethod.Post, new {start = true }))
{
 
         <input type="submit" value="Запустить парсер" class="btn btn-block" />

}