CatalogAppMVC/CatalogAppMVC/Models/Record.cs
using CatalogAppMVC.Models.interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CatalogAppMVC.Models
{
    public class Record
    {
        public enum StatusType { PREMODERATION, APPROVED, DECLINED }

        public int ID { get; private set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<Tag> Tags { get; set; }
        public List<Specification> Specifications { get; set; }
        public List<File> Files { get; set; }
        public int CategoryID { get; set; }
        public int UserAuthorID { get; set; }
        public StatusType Status { get; private set; }

        public Record(int userID, int categoryID)
        {
            ID = 0;
            CategoryID = categoryID;
            UserAuthorID = userID;
            Specifications = Specification.GetMandatSpecifications(CategoryID);
        }
        public Record()
        {
            ID = 0;
            CategoryID = 0;
            UserAuthorID = 0;
        }
        


        public void LoadFromPage(Record recordFromPage)
        {
            for (int i = 0; i < Specifications.Count; ++i)
            {
                Specifications[i].Value = recordFromPage.Specifications[i].Value;
            }
            Name = recordFromPage.Name;
            Description = recordFromPage.Description;
        }

        public void LoadTagsFromString(string tagsString)
        {
            Tags = Tag.CreateTagsFromString(tagsString);
        }




        //Методы для работы с БД

        public static Record GetRecord(int recordID)
        {
            IRepository repository = new Repository();
            Record record = null;
            try
            {
                WorkLinqToSql.Machinery mach = (from m in repository.Machinerys where m.Id == recordID select m).Single<WorkLinqToSql.Machinery>();
                record = repository.ToRecord(mach);
                if (record.Tags == null)
                    record.Tags = new List<Tag>();
                if (record.Files == null)
                    record.Files = new List<File>();
                if (record.Specifications == null)
                    record.Specifications = new List<Specification>();
            }
            catch
            {
                return null;
            }
            return record;
        }

        public static List<Record> GetAllRecords()
        {
            IRepository repository = new Repository();
            List<Record> list = new List<Record>();
            var recordsFromBase = from r in repository.Machinerys select r;
            foreach (WorkLinqToSql.Machinery machinery in recordsFromBase)
            {
                list.Add(repository.ToRecord(machinery));
            }
            return list;
        }

        public static List<Record> GetRecordsOfCategory(int categoryID)
        {
            List<Record> recordList = new List<Record>();
            IRepository repository = new Repository();

            try
            {
                var records = from rec in repository.Machinerys where rec.CatalogCategory.Id == categoryID select rec;
                foreach(var rec in records)
                {
                    recordList.Add(repository.ToRecord(rec));
                }
            }
            catch
            {
                return new List<Record>();
            }
            return recordList;
        }

        public void AddToDataBase()
        {
            IRepository repository = new Repository();
            ID = repository.CreateMachinery(this);
        }

        public void ChangeStatus(StatusType status)
        {
            if(ID != 0) //Id == 0 когда запись создана, но еще не добавлена в базу
            {
                IRepository repository = new Repository();
                if (repository.UpdateStatusMachinery(status, ID))
                {
                    Status = status;
                }
            }
        }

        public void SetID(int id)
        {
            ID = id;
        }
    }
}

CatalogAppMVC/CatalogAppMVC/Models/RecordsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CatalogAppMVC.Models
{
    public class RecordsViewModel
    {
        public List<Record> records;
        public int categoryID { get; set; }

        public List<RecordIdBool> RecordsForView { get; set; }
        

        public class RecordIdBool { public bool check {get; set;} public int id {get; set;}}


    }
}

CatalogAppMVC/CatalogAppMVC/Controllers/RecordsController.cs
using CatalogAppMVC.Models;
using CatalogAppMVC.Models.interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


using System.Configuration;
using Ninject;
using CatalogAppMVC.Models.Identity;
using System.Reflection;
using System.Threading;


namespace CatalogAppMVC.Controllers
{
    public class RecordsController : Controller
    {
        #region newRecord

        [Inject]
        public IRepository repo { get; set; }

        [HttpGet]
        public ActionResult AddRecord()
        {
            Record record = Session["Record"] as Record;
            return View(record);
        }

        [HttpPost]
        public ActionResult AddRecord(Record recordNew, string TagsString)
        {
            Record record = Session["Record"] as Record;
            record.Files = new List<Models.File>();
            record.LoadFromPage(recordNew);
            record.LoadTagsFromString(TagsString);

            Session["Record"] = record;
            return RedirectToAction("AddRecordFiles");
        }




        [HttpGet]
        public ActionResult AddRecordCategory()
        {
            int userID = Access.GetUserID(User, HttpContext);
            ViewBag.Categories = new SelectList(Category.GetCategoriesForWrite(userID), "Id", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult AddRecordCategory(int CategorySelected)
        {
            int userID = Access.GetUserID(User, HttpContext);
            //TODO Добавить проверку, правда ли пользователь выбрал одну из доступных ему категорий
            Session["Record"] = new Record(userID, CategorySelected);
            return RedirectToAction("AddRecord");
        }




        [HttpGet]
        public ActionResult AddRecordFiles()
        {
            return View(new FileView());
        }

        [HttpPost]
        public ActionResult AddRecordFiles(FileView fileView)
        {
            Record record = Session["Record"] as Record;
            int userID = Access.GetUserID(User, HttpContext);
            if(fileView.UploadedFile != null)
            {
                CatalogAppMVC.Models.File file = CatalogAppMVC.Models.File.UploadFile(fileView.UploadedFile.FileName, "/", userID, fileView.UploadedFile);
                if (file != null)
                    record.Files.Add(file);
            }
            else
            {
                return View(new FileView());
            }

            return View(new FileView());
        }

        public ActionResult CreateRecord()
        {
            Record record = Session["Record"] as Record;
            try
            {
                record.AddToDataBase();
                foreach(CatalogAppMVC.Models.File file in record.Files)
                {
                    file.RecordID = record.ID;
                    file.AddToBase();
                }
            }
            catch
            {

                
            }
            return RedirectToAction("Index", "Home");
        }


        #endregion

        #region OneRecordView

        public ActionResult RecordView(int recordID)
        {
            Record record = Record.GetRecord(recordID);
            return View(record);
        }
        public ActionResult TryDownloadFile(int fileID)
        {
            int userID = Access.GetUserID(User, HttpContext);
            if (Access.CanDownloadFile(userID, fileID))
            {
                return RedirectToAction("DownloadFile", new { FileID = fileID });
            }
            return View("DownloadFileError");
        }

        public ActionResult DownloadFile(int FileID)
        {
            CatalogAppMVC.Models.File file = CatalogAppMVC.Models.File.GetFile(FileID);
            if(file != null)
            {
                return File(file.GetPatchToFile(), CatalogAppMVC.Models.File.TYPEFILES, file.GetFileName());
            }
            return RedirectToAction("FileNotFound");
        }

        public ActionResult FileNotFound()
        {
            return View();
        }


        #endregion

        public ActionResult SomeRecordsView()
        {
            List<RecordsViewModel.RecordIdBool> records = Session["RecordsForComparison"] as List<RecordsViewModel.RecordIdBool>;
            List<Record> recordList = new List<Record>();
            foreach(RecordsViewModel.RecordIdBool rec in records)
            {
                if (rec.check)
                    recordList.Add(Record.GetRecord(rec.id));
            }
            MultipleRecordsForCompare multRecords = new MultipleRecordsForCompare(recordList);
            return View(multRecords);
        }
        [HttpGet]
        public ActionResult RecordsOfCategory(int categoryID)
        {
            int userID = Access.GetUserID(User, HttpContext);
            if (Access.CanReadCategory(userID, categoryID))
            {
                ViewBag.CategoryName = Category.GetCategory(categoryID).Name;

                var ViewModel = new RecordsViewModel();
                ViewModel.records = Record.GetRecordsOfCategory(categoryID);
                ViewModel.RecordsForView = new List<RecordsViewModel.RecordIdBool>();
                ViewModel.categoryID = categoryID;
                for (int i = 0; i < ViewModel.records.Count(); ++i)
                {
                    ViewModel.RecordsForView.Add(new RecordsViewModel.RecordIdBool());
                }
                return View(ViewModel);
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult RecordsOfCategory(RecordsViewModel model, int CategoryID)
        {
            foreach(RecordsViewModel.RecordIdBool rec in model.RecordsForView)
            {
                if(rec.check)
                {
                    Session["RecordsForComparison"] = model.RecordsForView;
                    return RedirectToAction("SomeRecordsView");
                }
            }
            return RedirectToAction("RecordsOfCategory", new { categoryID = CategoryID });
        }
    }
}

CatalogAppMVC/CatalogAppMVC/Views/Records/AddRecord.cshtml
@model CatalogAppMVC.Models.Record

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddRecord</title>
</head>
<body>
    <p>Шаг 2: описание</p>
    <div> 
        @using (Html.BeginForm())
        {
            <p>Название:</p>
            @Html.TextBoxFor(name => Model.Name)
            <p>Описание:</p>
            @Html.TextAreaFor(description => Model.Description)
            
            <div>
                <p>Спецификации:</p>
                @for (int i = 0; i < Model.Specifications.Count; ++i)
                {   
                    <p><b>@Model.Specifications[i].Name</b> @Html.TextBoxFor(val => Model.Specifications[i].Value)</p>
                }

            </div>
            <div>
                <p>Введите теги (через запятую)</p>
                @Html.TextBox("TagsString")
            </div>
        <p><input type="submit" value="Далее" /></p>
        }
    </div>
</body>
</html>

CatalogAppMVC/CatalogAppMVC/Views/Records/AddRecordCategory.cshtml
@model CatalogAppMVC.Models.Category
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddRecordCategory</title>
</head>
<body>
    <p>Шаг 1: выберите категорию</p>
    <div> 
        @using (Html.BeginForm())
        { 
            @Html.DropDownList("CategorySelected", ViewBag.Categories as SelectList)
            <p><input type="submit" value="Далее" /></p>
        }
    </div>
</body>
</html>

CatalogAppMVC/CatalogAppMVC/Views/Records/AddRecordFiles.cshtml
@model CatalogAppMVC.Models.FileView

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddRecordFiles</title>
</head>
<body>
    <p>Шаг 3: добавление файлов</p>
@using (Html.BeginForm("AddRecordFiles", "Records", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    <fieldset>
        <div class="control-group">
            <label class="control-label" for="Email">
                Загрузите файл:
            </label>
            <div class="controls">
                @Html.TextBox("UploadedFile", Model.UploadedFile, new { type = "file", @class = "input-xlarge" })
                @Html.ValidationMessage("UploadedFile")
            </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">
                Загрузить
            </button>
        </div>
    </fieldset>
}
    @Html.ActionLink("Создать запись", "CreateRecord")
</body>
</html>

CatalogAppMVC/CatalogAppMVC/Views/Records/DownloadFileError.cshtml
@{
    ViewBag.Title = "DownloadFileError";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DownloadFileError</h2>
ERROR!!!

CatalogAppMVC/CatalogAppMVC/Views/Records/FileNotFound.cshtml
@{
    ViewBag.Title = "FileNotFound";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ФАЙЛ НЕ НАЙДЕН</h2>

CatalogAppMVC/CatalogAppMVC/Views/Records/RecordView.cshtml
@model CatalogAppMVC.Models.Record
@using CatalogAppMVC.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@Model.Name</title>
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/RecordView.js")" type="text/javascript"></script>

    <link href="@Url.Content("~/Content/RecordView.css")" rel="stylesheet" type="text/css" />

</head>
<body>
    <div class="page-header">
        <h1><small>@Model.Name</small></h1>
    </div>
    <div id="photo">
        <img src="@Url.Content(@Image.GetHeadImageFromFiles(Model.Files))" />
    </div>
    <div id="text">
        @Model.Description
    </div>

    <div id="tags">
        @foreach (Tag t in Model.Tags)
        {
            <text>&lt;</text>@t.Name<text>&gt;</text>
        }
    </div>

    <div id="content">
        <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a href="#specifications" data-toggle="tab">Технические характеристики</a></li>
            <li><a href="#photos" data-toggle="tab">Фото</a></li>
            <li><a href="#documents" data-toggle="tab">Документы</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="specifications">
                <table class="table">
                    <tr>
                        <th>Характеристика</th>
                        <th>Значение</th>
                    </tr>
                    @foreach (Specification sp in Model.Specifications)
                    {
                        <tr>
                            <td>@sp.Name</td>
                            <td>@sp.Value</td>
                        </tr>
                    }
                </table>
            </div>
            <div class="tab-pane" id="photos">
                <table>
                    @foreach (CatalogAppMVC.Models.File file in Model.Files)
                    {
                        if (file.DocumentType == Image.IMAGE)
                        {
                            <tr>
                                <td>
                                    @file.DocumentName &#91; @file.DocumentType &#93;
                                </td>
                                <td>
                                    размер: @(@file.Size/1024) Мб
                                </td>
                                <td>
                                    загрузил: @file.AuthorName
                                </td>
                                <td>
                                    @Ajax.ActionLink("скачать", "TryDownloadFile", new { fileID = file.FileID }, new AjaxOptions { })
                                </td>
                            </tr>
                        }
                    }

                </table>
            </div>
            <div class="tab-pane" id="documents">
                <table>
                    @foreach (CatalogAppMVC.Models.File file in Model.Files)
                    {
                        if (file.DocumentType != Image.IMAGE && file.DocumentType != Image.IMAGEHEAD)
                        {
                            <tr>
                                <td>
                                    @file.DocumentName &#91; @file.DocumentType &#93;
                                </td>
                                <td>
                                    размер: @file.Size Мб
                                </td>
                                <td>
                                    загрузил: @file.AuthorName
                                </td>
                                <td>
                                    @Ajax.ActionLink("скачать", "TryDownloadFile", new { fileID = file.FileID }, new AjaxOptions { })
                                </td>
                            </tr>
                        }
                    }

                </table>
            </div>
        </div>

    </div>
</body>
</html>

CatalogAppMVC/CatalogAppMVC/Views/Records/RecordsOfCategory.cshtml
@model CatalogAppMVC.Models.RecordsViewModel

@{
    ViewBag.Title = "RecordsOfCategory1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.CategoryName</title>
</head>
<body>
    <h2>@ViewBag.CategoryName</h2>
    @Html.Hidden("CategoryID", Model.categoryID)
    @using (Html.BeginForm())
    {
        <ul class="list-group">
            @for (int i = 0; i < Model.records.Count; ++i)
            {
                <li class="list-group-item">
                    @Html.Hidden(String.Format("RecordsForView[{0}].id", i), Model.records[i].ID)
                    @Html.CheckBoxFor(val => Model.RecordsForView[i].check)
                    @Html.ActionLink(Model.records[i].Name, "RecordView", "Records", new { recordID = Model.records[i].ID }, null)
                </li>
            }
        </ul>
    <br />
    <br />
    <p><input type="submit" value="Сравнить" /></p>
    }
</body>
</html>

CatalogAppMVC/CatalogAppMVC/Views/Records/SomeRecordsView.cshtml
@model CatalogAppMVC.Models.MultipleRecordsForCompare

@{
    ViewBag.Title = "SomeRecordsView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Сравнение</h2>

<table class="table">
    <tr>
        <th>Характеристика</th>
        @foreach(string recordName in Model.RecordNames)
        {
            <th>@recordName</th>
        }
    </tr>
    @foreach (KeyValuePair<string, List<string>> sp in Model.GetSpecifications())
    {
        <tr>
            <td>@sp.Key</td>
            @foreach (string val in Model.GetSpecifications()[sp.Key])
            {
                if (val != null)
                {
                    <td>@val</td>
                }
                else
                {
                    <td>&mdash;</td>
                }
            }
        </tr>
    }
</table>

CatalogAppMVC/CatalogAppMVC/Views/Records/TwoRecordsView.cshtml
@model CatalogAppMVC.Models.MultipleRecordsForCompare

@{
    ViewBag.Title = "TwoRecordsView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>TwoRecordsView</h2>

<table class="table">
    <tr>
        <th>Характеристика</th>
        @foreach(string recordName in Model.RecordNames)
        {
            <th>@recordName</th>
        }
    </tr>
    @foreach (KeyValuePair<string, List<string>> sp in Model.GetSpecifications())
    {
        <tr>
            <td>@sp.Key</td>
            @foreach (string val in Model.GetSpecifications()[sp.Key])
            {
                if (val != null)
                {
                    <td>@val</td>
                }
                else
                {
                    <td>&mdash;</td>
                }
            }
        </tr>
    }
</table>